# Generated by Django 6.0.3 on 2026-04-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_emailanalysis_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(default=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='analyst_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='flagged_status',
            field=models.CharField(default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
