# Generated by Django 6.0.3 on 2026-04-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_detectionrule_emailanalysis_analyst_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailanalysis',
            name='is_false_positive',
        ),
    ]
