# Generated by Django 6.0.3 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_remove_emailanalysis_is_false_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailanalysis',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emailanalysis',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
